---
- name: Adds zookeeper user
  user:
    name: zookeeper
    home: "{{ zookeeper_install_dir }}"
    createhome: yes

- name: Adds zookeeper's bashrc
  become: true
  become_user: zookeeper
  template:
    src: bashrc.j2
    dest: "{{ zookeeper_install_dir  }}/.bashrc"

- name: Checks if zookeeper is already present
  stat:
    path: /etc/init.d/zookeeper
  register: __zookeeper_init

- name: Gets zookeeper tarball
  get_url:
    url: "{{ zookeeper_download_url }}"
    dest: "/tmp/zookeeper.tgz"
  register: __zookeeper_downloaded
  when: not __zookeeper_init.stat.exists

- name: Untars Zookeeper
  become: true
  become_user: zookeeper
  # Sorry, unarchive sucks
  command: tar xvzf /tmp/zookeeper.tgz -C {{ zookeeper_install_dir }} --strip-components=1
  when: __zookeeper_downloaded | changed
  notify: Restart Zookeeper

- name: Installs init script
  template:
    src: zookeeper.init.j2
    dest: /etc/init.d/zookeeper
    mode: 0770
    owner: root
    group: root
  notify: Restart Zookeeper

- name: Enables init script
  service:
    name: zookeeper
    enabled: true

- name: Creates log and PID dirs with proper ownership
  file: path={{ item }} state=directory owner=zookeeper group=zookeeper
  with_items:
    - /var/run/zookeeper/
    - /var/log/zookeeper/
    - "{{ zookeeper_datadir }}"

- name: Adds zookeeper config
  template:
    src: zoo.cfg.j2
    dest: "{{ zookeeper_install_dir }}/conf/zoo.cfg"
    mode: 0644
    owner: zookeeper
    group: zookeeper
  notify: Restart Zookeeper

- name: Adds zookeeper sysconfig
  template:
    src: zookeeper.j2
    dest: "/etc/sysconfig/zookeeper"
    mode: 0644
  notify: Restart Zookeeper

- name: Adds zookeeper server ID
  template:
    src: myid.j2
    dest: "{{ zookeeper_datadir }}/myid"
    mode: 0644
  notify: Restart Zookeeper

