#!/bin/bash
# -*- bash -*-

function ansible_fallback() {
  # Install a specific version of Ansible
  [[ -n $test_ansible_version ]] && install_ansible ${test_ansible_version}
}

# Accès au DSL RoleSpec
. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/defaults.conf"

# Configuration de l'utilisateur pour l'intégration continue'
if [ -z "${TRAVIS}" ]; then
  CI_USER="vagrant"
else
  CI_USER="${USER}"
fi

# Prérequis
## Installation de la version spécifiée d'ansible
## Voir defaults.conf

# Use preinstalled version of Ansible
if [ -d /usr/local/share/virtualenvs ]; then
  export WORKON_HOME=/usr/local/share/virtualenvs
  source /usr/bin/virtualenvwrapper.sh
  workon ${test_ansible_version} || ansible_fallback
else
  ansible_fallback
fi

## Installation des dépendances
[ -e requirements.yml ] && ansible-galaxy install -r requirements.yml

# Tests

# Test de syntaxe et test d'exécution correcte du playbook
assert_playbook_runs -e "ci_user=$CI_USER"
# Add -vvvv if you want it verbose

# Vérification de l'idempotence du playbook
assert_playbook_idempotent -e "ci_user=$CI_USER"